# https://github.com/vercel/next.js/blob/canary/examples/with-docker-compose/docker-compose.prod.yml

services:
  next-app:
    container_name: next-app
    build:
      context: $PWD
      dockerfile: Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000:3000
    # Set environment variables directly in the docker-compose file
    environment:
      API_KEY: ${ENV_VARIABLE}
    env_file:
    #      - ../../xx
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
